name: "Daily Covid Data Pull"
env:
    API_KEY: ${{ secrets.COVIDAPIKEY }}
on:
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *"

jobs:
  UpdateDate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Update Historical US Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalUSURL = 'https://api.covidactnow.org/v2/states.timeseries.json?apiKey=' + apiKey
            
            historicalUSResponse = urlopen(historicalUSURL)
            
            dataHistoricalUSJSON = json.loads(historicalUSResponse.read())
            
            updateFile = open("covidHistoricalUSData.js", "w")

            newHistoricalUSData = 'let historicalUSData = ' + json.dumps(dataHistoricalUSJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newHistoricalUSData)
            updateFile.close()
      - name: Update Current US Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            currentUSURL = 'https://api.covidactnow.org/v2/states.json?apiKey=' + apiKey

            currentUSResponse = urlopen(currentUSURL)

            dataCurrentUSJSON = json.loads(currentUSResponse.read())
            updateFile = open("covidCurrentUSData.js", "w")

            newCurrentUSData = 'let currentUSData = ' + json.dumps(dataCurrentUSJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newCurrentUSData)
            updateFile.close()
      - name: Update Historical State Covid Data
        timeout-minutes: 6
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalAllStates = 'https://api.covidactnow.org/v2/counties.timeseries.json?apiKey=' + apiKey

            historicalAllStatesResponse = urlopen(historicalAllStates)

            dataHistoricalAllStatesJSON = json.loads(historicalAllStatesResponse.read())

            updateFile = open("covidHistoricalStateData.js", "w")

            newHistoricalAllStatesData = 'let historicalAllStatesData = ' + json.dumps(dataHistoricalAllStatesJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newHistoricalAllStatesData)
            updateFile.close()
      - name: Update Current State Covid Data
        timeout-minutes: 6
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            currentAllStates = 'https://api.covidactnow.org/v2/counties.json?apiKey=' + apiKey

            currentAllStatesResponse = urlopen(currentAllStates)

            dataCurrentAllStatesJSON = json.loads(currentAllStatesResponse.read())

            updateFile = open("covidCurrentStateData.js", "w")

            newCurrentAllStatesData = 'let currentAllStatesData = ' + json.dumps(dataCurrentAllStatesJSON, indent=4, separators=(", ", " : "))

            updateFile.write(newCurrentAllStatesData)
            updateFile.close()
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            branch: main
            file-path: docs/data/*Data.js
            commit-msg: Daily Covid Data Pull
            github-token: ${{ secrets.GITHUB_TOKEN }}
