name: "Daily Covid Data Pull"
env:
    API_KEY: ${{ secrets.COVIDAPIKEY }}
on:
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *"

jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Update Historical Country Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalUSURL = 'https://api.covidactnow.org/v2/country/US.timeseries.json?apiKey=' + apiKey
            
            historicalUSResponse = urlopen(historicalUSURL)
            
            dataHistoricalUSJSON = json.loads(historicalUSResponse.read())
            
            updateFile = open("./docs/data/covidHistoricalUSData.js", "w")

            newHistoricalUSData = 'let historicalUSData = ' + json.dumps(dataHistoricalUSJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newHistoricalUSData)
            updateFile.close()
      - name: Update Current Country Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            currentUSURL = 'https://api.covidactnow.org/v2/country/US.json?apiKey=' + apiKey
            
            currentUSResponse = urlopen(currentUSURL)
            
            dataCurrentUSJSON = json.loads(currentUSResponse.read())
            
            updateFile = open("./docs/data/covidCurrentUSData.js", "w")

            newCurrentUSData = 'let currentUSData = ' + json.dumps(dataCurrentUSJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newCurrentUSData)
            updateFile.close()
      - name: Update Historical All States Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalAllStatesURL = 'https://api.covidactnow.org/v2/states.timeseries.json?apiKey=' + apiKey
            
            historicalAllStatesResponse = urlopen(historicalAllStatesURL)
            
            dataHistoricalAllStatesJSON = json.loads(historicalAllStatesResponse.read())
            
            updateFile = open("./docs/data/covidHistoricalStateData.js", "w")

            newHistoricalAllStatesData = 'let historicalAllStatesData = ' + json.dumps(dataHistoricalAllStatesJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newHistoricalAllStatesData)
            updateFile.close()
      - name: Update Current All States Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            currentAllStatesURL = 'https://api.covidactnow.org/v2/states.json?apiKey=' + apiKey

            currentAllStatesResponse = urlopen(currentAllStatesURL)

            dataCurrentAllStatesJSON = json.loads(currentAllStatesResponse.read())
            updateFile = open("./docs/data/covidCurrentStateData.js", "w")

            newCurrentAllStatesData = 'let currentAllStatesData = ' + json.dumps(dataCurrentAllStatesJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newCurrentAllStatesData)
            updateFile.close()
        
      - name: Update Current All Counties Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            currentAllCounties = 'https://api.covidactnow.org/v2/counties.json?apiKey=' + apiKey

            currentAllCountiesResponse = urlopen(currentAllCounties)

            dataCurrentAllCountiesJSON = json.loads(currentAllCountiesResponse.read())

            updateFile = open("./docs/data/covidCurrentCountyData.js", "w")

            newCurrentAllCountiesData = 'let currentAllCountiesData = ' + json.dumps(dataCurrentAllCountiesJSON, indent=4, separators=(", ", " : "))

            updateFile.write(newCurrentAllCountiesData)
            updateFile.close()
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            branch: main
            file-path: |
                docs/data/covidCurrentStateData.js
                docs/data/covidCurrentCountyData.js
                docs/data/covidHistoricalStateData.js
                docs/data/covidHistoricalUSData.js
                docs/data/covidCurrentUSData.js
            commit-msg: Daily Covid Data Pull
            github-token: ${{ secrets.GITHUB_TOKEN }}
