name: "Daily Covid Data Pull"
env:
    API_KEY: ${{ secrets.COVIDAPIKEY }}
on:
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *"

jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Update Historical US Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalUSURL = 'https://api.covidactnow.org/v2/states.timeseries.json?apiKey=' + apiKey
            
            historicalUSResponse = urlopen(historicalUSURL)
            
            dataHistoricalUSJSON = json.loads(historicalUSResponse.read())
            
            updateFile = open("./docs/data/covidHistoricalUSData.js", "w")

            newHistoricalUSData = 'let historicalUSData = ' + json.dumps(dataHistoricalUSJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newHistoricalUSData)
            updateFile.close()
      - name: Update Current US Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            currentUSURL = 'https://api.covidactnow.org/v2/states.json?apiKey=' + apiKey

            currentUSResponse = urlopen(currentUSURL)

            dataCurrentUSJSON = json.loads(currentUSResponse.read())
            updateFile = open("./docs/data/covidCurrentUSData.js", "w")

            newCurrentUSData = 'let currentUSData = ' + json.dumps(dataCurrentUSJSON, indent=4, separators=(", ", " : "))
            
            updateFile.write(newCurrentUSData)
            updateFile.close()
        
      - name: Update Historical Alabama Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalAllStates = 'https://api.covidactnow.org/v2/county/AL.timeseries.json?apiKey=' + apiKey

            historicalAllStatesResponse = urlopen(historicalAllStates)

            dataHistoricalAllStatesJSON = json.loads(historicalAllStatesResponse.read())

            updateFile = open("./docs/data/covidHistoricalStateData.js", "w")

            newHistoricalAllStatesData = 'let historicalAllStatesData = [ "AL" : ' + json.dumps(dataHistoricalAllStatesJSON, indent=4, separators=(", ", " : ")) + ',\n'
            
            updateFile.write(newHistoricalAllStatesData)
            updateFile.close()
    
      - name: Update Historical Alaska Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalAllStates = 'https://api.covidactnow.org/v2/county/AK.timeseries.json?apiKey=' + apiKey

            historicalAllStatesResponse = urlopen(historicalAllStates)

            dataHistoricalAllStatesJSON = json.loads(historicalAllStatesResponse.read())

            updateFile = open("./docs/data/covidHistoricalStateData.js", "a")

            newHistoricalAllStatesData = '"AK" : ' + json.dumps(dataHistoricalAllStatesJSON, indent=4, separators=(", ", " : ")) + ',\n'
            
            updateFile.write(newHistoricalAllStatesData)
            updateFile.close()

      - name: Update Historical Arizona Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalAllStates = 'https://api.covidactnow.org/v2/county/AZ.timeseries.json?apiKey=' + apiKey

            historicalAllStatesResponse = urlopen(historicalAllStates)

            dataHistoricalAllStatesJSON = json.loads(historicalAllStatesResponse.read())

            updateFile = open("./docs/data/covidHistoricalStateData.js", "a")

            newHistoricalAllStatesData = '"AZ" : ' + json.dumps(dataHistoricalAllStatesJSON, indent=4, separators=(", ", " : ")) + ',\n'
            
            updateFile.write(newHistoricalAllStatesData)
            updateFile.close()

      - name: Update Historical Arkansas Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            historicalAllStates = 'https://api.covidactnow.org/v2/county/AR.timeseries.json?apiKey=' + apiKey

            historicalAllStatesResponse = urlopen(historicalAllStates)

            dataHistoricalAllStatesJSON = json.loads(historicalAllStatesResponse.read())

            updateFile = open("./docs/data/covidHistoricalStateData.js", "a")

            newHistoricalAllStatesData = '"AR" : ' + json.dumps(dataHistoricalAllStatesJSON, indent=4, separators=(", ", " : ")) + '\n]\n'
            
            updateFile.write(newHistoricalAllStatesData)
            updateFile.close()
            
      - name: Update Current State Covid Data
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            apiKey = os.environ['API_KEY'];
            currentAllStates = 'https://api.covidactnow.org/v2/counties.json?apiKey=' + apiKey

            currentAllStatesResponse = urlopen(currentAllStates)

            dataCurrentAllStatesJSON = json.loads(currentAllStatesResponse.read())

            updateFile = open("./docs/data/covidCurrentStateData.js", "w")

            newCurrentAllStatesData = 'let currentAllStatesData = ' + json.dumps(dataCurrentAllStatesJSON, indent=4, separators=(", ", " : "))

            updateFile.write(newCurrentAllStatesData)
            updateFile.close()
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            branch: main
            file-path: |
                docs/data/covidCurrentStateData.js
                docs/data/covidHistoricalStateData.js
                docs/data/covidCurrentUSData.js
                docs/data/covidHistoricalUSData.js
            commit-msg: Daily Covid Data Pull
            github-token: ${{ secrets.GITHUB_TOKEN }}
