name: "Daily Covid Data Pull"
on:
  workflow_dispatch:
  schedule:
  - cron: "19 10 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Fetch resources
        run: ./scripts/fetch-resources.sh
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import json
            from urllib.request import urlopen

            historicalURL = 'https://api.covidtracking.com/v1/us/daily.json'
            currentURL = 'https://api.covidtracking.com/v1/us/current.json'

            historicalResponse = urlopen(historicalURL)
            currentResponse = urlopen(historicalURL)

            dataHistoricalJSON = json.loads(historicalResponse.read())
            dataCurrentJSON = json.loads(currentResponse.read())

            updateFile = open("/docs/data/covidData.js", "w")

            newHistoricalData = 'let historicalData = ' + json.dumps(dataHistoricalJSON, indent=4, separators=(", ", " : "))
            newCurrentData = 'let currentData = ' + json.dumps(dataCurrentJSON, indent=4, separators=(", ", " : "))

            updateFile.write(newHistoricalData  + '\n' + newCurrentData)
            updateFile.close()
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            branch: main
            file-path: docs/data/covidData.js
            commit-msg: Daily Covid Data Pull
            github-token: ${{ secrets.GITHUB_TOKEN }}
